### ISSUE TITLE
"make install" does not install las.hpp

### ISSUE THREAD

**Issue by wonder-sk** [hobuinc/laz-perf#124]
QGIS uses a couple of structs from `las.hpp`, but this header and other headers that it #includes do not get installed with `make install`. Is it intentional (private API) or is it a bug?

```cpp
#include "lazperf/las.hpp"

lazperf::las::point10 p;
lazperf::las::gpstime gps;
lazperf::las::rgb rgb;
```

**Comment by abellgithub** [comment]
It is intentional. You're welcome to copy the file if you like, but the structures in `las.hpp` are not part of the public interface and could change.
