### ISSUE TITLE
Segfault on writing file with no points

### ISSUE THREAD

**Issue by CCInc** [hobuinc/laz-perf#138]
To reproduce:

```
    writer::named_file::config c({0.01,0.01,0.01}, {0.0,0.0,0.0});
    writer::named_file out(tempfile, c);
    out.close(); // <- Segfault
```

The issue is due to `pcompressor` never getting set as `writePoints` is never called. However, writing an empty file should be a valid operation.

**Comment by hobu** [comment]
Fix implemented in #139
