### ISSUE TITLE
Multi-threaded encoding/compression?

### ISSUE THREAD

**Issue by nigels-com** [hobuinc/laz-perf#142]
I don't have any hands-on experience with laz-perf so this is more of a question than an issue.

I'm interested in multi-threaded LAZ-writing and I do get the impression this API might facilitate
multiple threads each encoding separate chunks, and a main thread "gathering" and outputting
those in the appropriate order.

Just curious if there are any known obstacles in the way of doing that?
In the context of garden variety Windows and Linux binaries.

**Comment by hobu** [comment]
These three projects should be inspirational in regards to laz-perf usage:

* https://github.com/hobuinc/untwine
* https://github.com/connormanning/copc.js
* https://github.com/PDAL/PDAL/
