### ISSUE TITLE
Add tests for emscripten

### ISSUE THREAD

**Issue by abellgithub** [hobuinc/laz-perf#57]
We have tests for C++, but we've found that things on Emscripten are sometimes different for various reasons (size of types, compiler issues).  It would be good to have verification that things work on Emscripten as well as a C++ compiled environment.

**Comment by connormanning** [comment]
I added some simple tests, one that reads from a [chunk](https://github.com/hobuinc/laz-perf/blob/js/js/src/test/chunk.test.ts) and one that reads a [file](https://github.com/hobuinc/laz-perf/blob/js/js/src/test/file.test.ts).  It's certainly not a full test suite but at least provides a sanity check that the WASM bindings have been generated properly and that they can do a "hello world" level of data decompression.  Combined with the existing exhaustive C++ test suite I think this provides pretty a decent level of coverage/confidence.  These JS tests can be expanded in the future as needed but I think they are good enough to call this ticket done.
